// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"github.com/coze-dev/coze-studio/backend/api/model/crossdomain/modelmgr"
	"github.com/coze-dev/coze-studio/backend/infra/contract/chatmodel"
	"gorm.io/gorm"
)

const TableNameModelMeta = "model_meta"

// ModelMeta 模型元信息
type ModelMeta struct {
	ID          int64                    `gorm:"column:id;primaryKey;comment:主键ID" json:"id"`                                                           // 主键ID
	ModelName   string                   `gorm:"column:model_name;not null;comment:模型名称" json:"model_name"`                                             // 模型名称
	Protocol    string                   `gorm:"column:protocol;not null;comment:模型协议" json:"protocol"`                                                 // 模型协议
	IconURI     string                   `gorm:"column:icon_uri;not null;comment:Icon URI" json:"icon_uri"`                                             // Icon URI
	Capability  *modelmgr.Capability     `gorm:"column:capability;comment:模型能力;serializer:json" json:"capability"`                                      // 模型能力
	ConnConfig  *chatmodel.Config        `gorm:"column:conn_config;comment:模型连接配置;serializer:json" json:"conn_config"`                                  // 模型连接配置
	Status      modelmgr.ModelMetaStatus `gorm:"column:status;not null;default:1;comment:模型状态;serializer:json" json:"status"`                           // 模型状态
	Description string                   `gorm:"column:description;not null;comment:模型描述" json:"description"`                                           // 模型描述
	CreatedAt   int64                    `gorm:"column:created_at;not null;autoCreateTime:milli;comment:Create Time in Milliseconds" json:"created_at"` // Create Time in Milliseconds
	UpdatedAt   int64                    `gorm:"column:updated_at;not null;autoUpdateTime:milli;comment:Update Time in Milliseconds" json:"updated_at"` // Update Time in Milliseconds
	DeletedAt   gorm.DeletedAt           `gorm:"column:deleted_at;comment:Delete Time in Milliseconds" json:"deleted_at"`                               // Delete Time in Milliseconds
	IconURL     string                   `gorm:"column:icon_url;not null;comment:Icon URL" json:"icon_url"`                                             // Icon URL
}

// TableName ModelMeta's table name
func (*ModelMeta) TableName() string {
	return TableNameModelMeta
}
