// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"github.com/coze-dev/coze-studio/backend/api/model/crossdomain/modelmgr"
	"gorm.io/gorm"
)

const TableNameModelEntity = "model_entity"

// ModelEntity 模型信息
type ModelEntity struct {
	ID            int64                      `gorm:"column:id;primaryKey;comment:主键ID" json:"id"`                                                           // 主键ID
	MetaID        int64                      `gorm:"column:meta_id;not null;comment:模型元信息 id" json:"meta_id"`                                               // 模型元信息 id
	Name          string                     `gorm:"column:name;not null;comment:名称" json:"name"`                                                           // 名称
	Description   string                     `gorm:"column:description;comment:描述" json:"description"`                                                      // 描述
	DefaultParams []*modelmgr.Parameter      `gorm:"column:default_params;comment:默认参数;serializer:json" json:"default_params"`                              // 默认参数
	Scenario      modelmgr.Scenario          `gorm:"column:scenario;not null;comment:模型应用场景;serializer:json" json:"scenario"`                               // 模型应用场景
	Status        modelmgr.ModelEntityStatus `gorm:"column:status;not null;default:1;comment:模型状态;serializer:json" json:"status"`                           // 模型状态
	CreatedAt     int64                      `gorm:"column:created_at;not null;autoCreateTime:milli;comment:Create Time in Milliseconds" json:"created_at"` // Create Time in Milliseconds
	UpdatedAt     int64                      `gorm:"column:updated_at;not null;autoUpdateTime:milli;comment:Update Time in Milliseconds" json:"updated_at"` // Update Time in Milliseconds
	DeletedAt     gorm.DeletedAt             `gorm:"column:deleted_at;comment:Delete Time in Milliseconds" json:"deleted_at"`                               // Delete Time in Milliseconds
}

// TableName ModelEntity's table name
func (*ModelEntity) TableName() string {
	return TableNameModelEntity
}
